name: ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  flutter:
    runs-on: ubuntu-latest
    steps:
      - name: check out source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: set up java
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95
        with:
          distribution: temurin
          java-version: "17"

      - name: set up flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2
        with:
          flutter-version-file: .fvmrc
          cache: true

      - name: get dependencies
        run: flutter pub get

      - name: analyze
        run: flutter analyze

      - name: test
        run: flutter test
